config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'application#one'
  get 'one' => 'application#one'
  get 'two' => 'application#two'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/one.html.erb
<h1>Turbolinks Scroll Position Bug</h1>

<p>When a Turbolinks page becomes "invalid" i.e. its tracked assets change or the <code>turbolinks-visit-control</code> directive is "reload", Turbolinks triggers a full page reload. Unfortunately this can result in an odd experience when navigating between scrollable pages—a user transitions to a new page but is returned to the scroll position of the previous page. This is becuase browsers cache the scroll position and restore it when a page is reloaded via <code>window.location.reload</code>.</p>

<p>This app aims to demonstrate the fix at <%= link_to 'https://github.com/turbolinks/turbolinks/pull/420' %></p>

<ol>
  <li>Scroll down</li>
  <li>Click the "Page Two" link (this loads a page with the <code>turbolinks-visit-control … reload</code> directive)</li>
  <li>Observe that the scroll position is correctly at the top</li>
</ol>

<p>Page one</p>
<p>Page one</p>
<p>Page one</p>
<p>Page one</p>
<p>Page one</p>
<p>Page one</p>
<p>Page one</p>
<p>Page one</p>
<p>Page one</p>
<p>Page one</p>
<p>Page one</p>
<p>Page one</p>
<p>Page one</p>
<p>Page one</p>
<p>Page one</p>
<p>Page one</p>
<p>Page one</p>
<p>Page one</p>
<p>Page one</p>
<p>Page one</p>
<p>Page one</p>
<p>Page one</p>
<p>Page one</p>
<p>Page one</p>
<p>Page one</p>
<p>Page one</p>
<p>Page one</p>
<p>Page one</p>
<p>Page one</p>
<p>Page one</p>
<p>Page one</p>
<p>Page one</p>
<p>Page one</p>
<p>Page one</p>
<p>Page one</p>
<p>Page one</p>
<p>Page one</p>
<p>Page one</p>

<%= link_to 'Page Two', two_path %>

app/views/application/two.html.erb
<% @turbolinks_visit_control = 'reload' %>

<h1>Page Two</h1>

<p>This page contains the <code>turbolinks-visit-control</code> directive, set to "reload".</p>

<p>Page two</p>
<p>Page two</p>
<p>Page two</p>
<p>Page two</p>
<p>Page two</p>
<p>Page two</p>
<p>Page two</p>
<p>Page two</p>
<p>Page two</p>
<p>Page two</p>
<p>Page two</p>
<p>Page two</p>
<p>Page two</p>
<p>Page two</p>
<p>Page two</p>
<p>Page two</p>
<p>Page two</p>
<p>Page two</p>
<p>Page two</p>
<p>Page two</p>
<p>Page two</p>
<p>Page two</p>
<p>Page two</p>
<p>Page two</p>
<p>Page two</p>
<p>Page two</p>
<p>Page two</p>
<p>Page two</p>
<p>Page two</p>
<p>Page two</p>
<p>Page two</p>
<p>Page two</p>
<p>Page two</p>
<p>Page two</p>
<p>Page two</p>
<p>Page two</p>
<p>Page two</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TurbolinksPageInvalidScrollTest</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <% if @turbolinks_visit_control %>
      <meta name="turbolinks-visit-control" content="<%= @turbolinks_visit_control %>">
    <% end %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>